name: HELLO WORLD
on: 
  - push
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: echo-hello-world
      run: echo "Hola, Mundo!!"

    - name: fail-step
      run: exit 1